---
all:
  vars:
    ansible_user: ubuntu
  children:
    pki_ca_host:
      hosts:
        localhost:
          ansible_connection: local
    load_balancer:
      hosts:
        localhost:
          ansible_connection: local
    consul_servers:
      hosts: {}
    consul_clients:
      hosts: {}
    nomad_servers:
      hosts: {}
    nomad_clients:
      hosts: {}
    vault_servers:
      hosts: {}
