vault_version: "1.21.1"
vault_package: >-
  {{
    'vault'
    if vault_version is not defined or vault_version == 'latest'
    else
      (
        'vault=' + vault_version + '*'
        if (ansible_facts | default({})).get('os_family', '') == 'Debian'
        else 'vault-' + vault_version + '*'
      )
  }}

vault_user: vault
vault_group: vault
vault_config_file: "{{ vault_config_dir }}/vault.hcl"

vault_config_dir: /etc/vault.d
vault_data_dir: /opt/vault
vault_tls_dir: /etc/vault.d/tls

vault_api_addr: "https://{{ node_ip | default(ansible_host) | default(inventory_hostname) }}:8200"
vault_cluster_addr: "https://{{ node_ip | default(ansible_host) | default(inventory_hostname) }}:8201"
vault_listener_address: "0.0.0.0:8200"
vault_cluster_listen_address: "0.0.0.0:8201"
vault_ui: true
vault_disable_mlock: false

vault_storage_backend: consul
vault_consul_address: "127.0.0.1:8501"
vault_consul_token: ""
vault_consul_scheme: "{{ 'https' if (consul_tls_enabled | default(true)) else 'http' }}"
vault_consul_tls_ca_file: "{{ vault_tls_dir }}/ca.pem"
vault_consul_tls_cert_file: "{{ vault_tls_dir }}/cert.pem"
vault_consul_tls_key_file: "{{ vault_tls_dir }}/key.pem"

vault_tls_enabled: true
vault_tls_source: pki
vault_tls_ca_src: "{{ pki_root | default(playbook_dir + '/pki') }}/ca/ca.pem"
vault_tls_cert_src: "{{ pki_root | default(playbook_dir + '/pki') }}/hosts/{{ inventory_hostname }}/cert.pem"
vault_tls_key_src: "{{ pki_root | default(playbook_dir + '/pki') }}/hosts/{{ inventory_hostname }}/key.pem"
vault_tls_require_client_cert: false

vault_seal_type: none
vault_seal_config: {}
