nomad_version: "1.11.1"
nomad_package: >-
  {{
    'nomad'
    if nomad_version is not defined or nomad_version == 'latest'
    else
      (
        'nomad=' + nomad_version
        if (ansible_facts | default({})).get('os_family', '') == 'Debian'
        else 'nomad-' + nomad_version + '*'
      )
  }}

nomad_user: nomad
nomad_group: nomad
nomad_config_file: "{{ nomad_config_dir }}/nomad.hcl"

nomad_server_enabled: false
nomad_client_enabled: false
nomad_bootstrap_expect: 1

nomad_region: global
nomad_datacenter: dc1
nomad_data_dir: /opt/nomad
nomad_config_dir: /etc/nomad.d
nomad_tls_dir: /etc/nomad.d/tls
nomad_bind_addr: "{{ ansible_host | default(inventory_hostname) }}"
nomad_advertise_addr: "{{ ansible_host | default(inventory_hostname) }}"
nomad_retry_join: []
nomad_retry_join_cloud_enabled: false
nomad_retry_join_cloud: []

nomad_consul_enabled: true
nomad_consul_address: "127.0.0.1:8500"
nomad_consul_token: ""
nomad_consul_tls_enabled: "{{ consul_tls_enabled | default(false) }}"
nomad_consul_tls_dir: /etc/nomad.d/consul-tls
nomad_consul_tls_ca_src: "{{ consul_tls_ca_src | default(pki_root + '/ca/ca.pem') }}"
nomad_consul_tls_cert_src: >-
  {{ consul_tls_cert_src | default(pki_root + '/hosts/' + inventory_hostname + '/cert.pem') }}
nomad_consul_tls_key_src: >-
  {{ consul_tls_key_src | default(pki_root + '/hosts/' + inventory_hostname + '/key.pem') }}

nomad_enable_raw_exec: false
nomad_acl_enabled: false

nomad_tls_enabled: true
nomad_tls_verify_server_hostname: true
nomad_tls_source: pki
nomad_tls_ca_src: "{{ pki_root }}/ca/ca.pem"
nomad_tls_cert_src: "{{ pki_root }}/hosts/{{ inventory_hostname }}/cert.pem"
nomad_tls_key_src: "{{ pki_root }}/hosts/{{ inventory_hostname }}/key.pem"
