---
all:
  vars:
    ansible_user: ubuntu
  children:
    pki_ca_host:
      hosts:
        localhost:
          ansible_connection: local
    load_balancer:
      hosts:
        localhost:
          ansible_connection: local
    consul_servers:
      hosts:
        core-1:
          ansible_host: 10.10.0.11
        core-2:
          ansible_host: 10.10.0.12
        core-3:
          ansible_host: 10.10.0.13
    consul_clients:
      hosts:
        worker-1:
          ansible_host: 10.10.0.21
    nomad_servers:
      hosts:
        core-1:
          ansible_host: 10.10.0.11
        core-2:
          ansible_host: 10.10.0.12
        core-3:
          ansible_host: 10.10.0.13
    nomad_clients:
      hosts:
        worker-1:
          ansible_host: 10.10.0.21
    vault_servers:
      hosts:
        core-1:
          ansible_host: 10.10.0.11
        core-2:
          ansible_host: 10.10.0.12
        core-3:
          ansible_host: 10.10.0.13
