---
all:
  vars:
    ansible_user: bash
  children:
    pki_ca_host:
      hosts:
        localhost:
          ansible_connection: local
    load_balancer:
      hosts:
        localhost:
          ansible_connection: local
    consul_servers:
      hosts:
        core-1:
          ansible_host: 10.10.110.118
        core-2:
          ansible_host: 10.10.110.119
        core-3:
          ansible_host: 10.10.110.120
    consul_clients:
      hosts:
        core-1:
        core-2:
        core-3:
    nomad_servers:
      hosts:
        core-1:
          ansible_host: 10.10.110.118
        core-2:
          ansible_host: 10.10.110.119
        core-3:
          ansible_host: 10.10.110.120
    nomad_clients:
      hosts:
        core-1:
        core-2:
        core-3:
    vault_servers:
      hosts:
        core-1:
          ansible_host: 10.10.110.118
        core-2:
          ansible_host: 10.10.110.119
        core-3:
          ansible_host: 10.10.110.120
