---
consul_version: "1.22.2"
consul_package: >-
  {{
    'consul'
    if consul_version is not defined or consul_version == 'latest'
    else
      (
        'consul=' + consul_version + '*'
        if (ansible_facts | default({})).get('os_family', '') == 'Debian'
        else 'consul-' + consul_version + '*'
      )
  }}

consul_user: consul
consul_group: consul
consul_config_file: "{{ consul_config_dir }}/consul.hcl"

consul_server: false  # Auto-set in tasks based on inventory group
consul_bootstrap_expect: 1  # Auto-calculated in tasks based on consul_servers group size

consul_datacenter: dc1
consul_data_dir: /opt/consul
consul_config_dir: /etc/consul.d
consul_tls_dir: /etc/consul.d/tls
consul_http_port: 8500
consul_https_port: 8501
consul_http_disable: true
consul_bind_addr: "{{ node_ip | default(ansible_host) | default(inventory_hostname) }}"
consul_advertise_addr: "{{ node_ip | default(ansible_host) | default(inventory_hostname) }}"
consul_client_addr: "0.0.0.0"
consul_retry_join: []
consul_retry_join_cloud_enabled: false
consul_retry_join_cloud: []
consul_encrypt: ""
consul_ui: true
consul_connect_enabled: true

consul_acl_enabled: true
consul_acl_default_policy: deny
consul_acl_down_policy: extend-cache
consul_acl_agent_token: ""
consul_acl_default_token: ""
consul_acl_replication_token: ""

consul_tls_enabled: true
consul_tls_source: pki
consul_tls_ca_src: "{{ pki_root | default(playbook_dir + '/pki') }}/ca/ca.pem"
consul_tls_cert_src: "{{ pki_root | default(playbook_dir + '/pki') }}/hosts/{{ inventory_hostname }}/cert.pem"
consul_tls_key_src: "{{ pki_root | default(playbook_dir + '/pki') }}/hosts/{{ inventory_hostname }}/key.pem"
