---
- name: Configure logrotate for HashiCorp services
  ansible.builtin.copy:
    dest: /etc/logrotate.d/hashicorp
    content: |
      /var/log/consul/*.log {
        daily
        rotate 14
        compress
        delaycompress
        missingok
        notifempty
        create 0644 consul consul
        sharedscripts
        postrotate
          systemctl reload consul > /dev/null 2>&1 || true
        endscript
      }

      /var/log/nomad/*.log {
        daily
        rotate 14
        compress
        delaycompress
        missingok
        notifempty
        create 0644 nomad nomad
        sharedscripts
        postrotate
          systemctl reload nomad > /dev/null 2>&1 || true
        endscript
      }
      /var/log/vault/*.log {
        daily
        rotate 14
        compress
        delaycompress
        missingok
        notifempty
        create 0644 vault vault
        sharedscripts
        postrotate
          systemctl reload vault > /dev/null 2>&1 || true
        endscript
      }
    mode: "0644"
  become: true
