---
# Cloud auto-join (GCP)
consul_retry_join_cloud_enabled: true
consul_retry_join_cloud:
  - "provider=gce project_name=my-project tag_value=consul-server"

nomad_retry_join_cloud_enabled: true
nomad_retry_join_cloud:
  - "provider=gce project_name=my-project tag_value=nomad-server"
