---
- name: Reload nomad
  ansible.builtin.systemd:
    name: nomad
    state: reloaded
  become: true

- name: Restart nomad
  ansible.builtin.systemd:
    name: nomad
    state: restarted
  become: true
